openapi: 3.0.2
info:
  title: 'News_Portal'
  version: "0.1"
paths:
  /api/news/:
    get:
      operationId: getAllNews
      description: 'Успешный ответ со списком новостей'
      parameters: []
      responses:
        '200':
          content:
          application/json:
            schema:
              type: array
              items:
                  $ref: '#/components/schemas/Post'
          description: ''
      tags:
        - news
  /news/create/:
    post:
      operationId: createPost
      description: 'Создание поста'
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
          description: ''
      tags:
        - create_news

components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 255
        text:
          type: string

      required:
        - title
